name: Build NPM Lib

on:
  workflow_call:

env:
  APP_NAME: piccy

jobs:
  build_windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64

    steps:
      - name: 检出仓库
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 设置 rust
        uses: puniyu/setup-rust@main
        with:
          target: ${{ matrix.platform.target }}
          save-cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.25.0
          run_install: true

      - name: 构建
        run: |
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: piccy_node

      - name: 上传构建产物
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            piccy_node/dist/${{ env.APP_NAME }}*.node

  build_macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64
          - runner: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    steps:
      - name: 检出仓库
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 设置 rust
        uses: puniyu/setup-rust@main
        with:
          target: ${{ matrix.platform.target }}
          save-cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.25.0
          run_install: true

      - name: 构建
        run: |
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: piccy_node

      - name: 上传构建产物
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            piccy_node/dist/${{ env.APP_NAME }}*.node

  build_linux:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
            container: ghcr.io/puniyu/debian:latest
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64
            container: ghcr.io/puniyu/debian:latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 设置 rust
        uses: puniyu/setup-rust@main
        with:
          target: ${{ matrix.platform.target }}
          save-cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.25.0
          run_install: true

      - name: 构建
        run: |
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: piccy_node

      - name: 上传构建产物
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            piccy_node/dist/${{ env.APP_NAME }}*.node
  

  build_wasm:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: wasm32-wasip1-threads
            label: wasm32-wasi

    steps:
      - name: 检出仓库
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 设置 rust
        uses: puniyu/setup-rust@main
        with:
          target: ${{ matrix.platform.target }}
          save-cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.25.0
          run_install: true

      - name: 构建
        run: |
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: piccy_node

      - name: 上传构建产物
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            piccy_node/dist/piccy.wasm32-wasi.wasm


      - name: 上传npm包
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "npm-package"
          path: |
            piccy_node/dist/index.js
            piccy_node/dist/index.d.ts
            piccy_node/package.json      

      - name: 上传npm包
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "npm-wasm"
          path: |
            piccy_node/dist/piccy.wasi.cjs
            piccy_node/dist/piccy.wasi-browser.js
            piccy_node/dist/wasi-worker.mjs
            piccy_node/dist/wasi-worker-browser.mjs