name: release
on:
  push:
    branches:
      - main
  pull_request_target:
    branches-ignore:
      - 'release-please**'
  workflow_dispatch:

env:
  APP_NAME: piccy

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.release-please.outputs['piccy_core--release_created'] }}
      app: ${{ steps.release-please.outputs['piccy_app--release_created'] }}
      app_tag_name: ${{ steps.release-please.outputs['piccy_app--tag_name'] }}
      node: ${{ steps.release-please.outputs['piccy_node--release_created'] }}
      node_tag_name: ${{ steps.release-please.outputs['piccy_node--tag_name'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  publish-crates-io:
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.outputs.core
    steps:
      - name: 检出仓库
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 设置 rust
        uses: puniyu/setup-rust@main
        with:
          save-cache: true
          prefix-key: ${{ env.APP_NAME }}
          tools: tauri-cli

      - name: 发布piccy_core
        run: |
          cargo publish --package piccy_core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

  build-tauri-app:
    needs: release
    uses: ./.github/workflows/build-tauri-app.yaml
    secrets: inherit


  publish-tauri-app:
    needs: [ build-tauri-app, release ]
    if : needs.release.outputs.app
    runs-on: ubuntu-latest
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 下载构建产物
        uses: dawidd6/action-download-artifact@v11
        with:
          name: ^piccy-app.*
          name_is_regexp: true
          skip_unpack: true

      - name: 上传Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            piccy-app-*
          tag_name: ${{ needs.release.outputs.app_tag_name }}

  build-npm-lib:
    if: needs.release.outputs.node
    needs: release
    uses: ./.github/workflows/build-npm-lib.yaml

  publish-npm-lib:
    needs: [ build-npm-lib, release ]
    if: needs.release.outputs.node
    runs-on: ubuntu-latest
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 下载npm包
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: "npm-package"
          path: piccy-node

      - name: 下载wasm包
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: "npm-wasm"
          path: piccy-node

      - name: 下载构建产物
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: piccy-node*
          path: piccy-node/artifacts

      - uses: pnpm/action-setup@v4
        with:
          version: 10.25.0

      - name: 发布npm包
        run: |
          pnpm install
          pnpm config set provenance true
          pnpm config set registry https://registry.npmjs.org/
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          pnpm run create-npm-dirs
          pnpm run artifacts
          pnpm publish --access public
        working-directory: piccy-node
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 上传Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            piccy-node/artifacts/piccy-node-*/piccy*.node
            piccy-node/artifacts/piccy-node-*/piccy*.wasm
          tag_name: ${{ needs.release.outputs.node_tag_name }}